package app.pony.companion.ui

/** Things only the activity can do: system settings, permission prompts, and intents. */
class PonyActions(
    val openAccessibility: () -> Unit = {},
    val openAppDetails: () -> Unit = {},
    val requestNotifications: () -> Unit = {},
    val requestCamera: () -> Unit = {},
    val requestMic: (listenAfter: Boolean) -> Unit = {},
    val requestBattery: () -> Unit = {},
    val openSamsungBattery: () -> Unit = {},
    val openKeyboardSettings: () -> Unit = {},
    val showKeyboardPicker: () -> Unit = {},
    val openAssistantSettings: () -> Unit = {},
    val openFullScreenSettings: () -> Unit = {},
    val openInstallPermission: () -> Unit = {},
    val pair: (String) -> Unit = {},
    val usePending: () -> Unit = {},
    val disconnect: () -> Unit = {},
    val reconnect: () -> Unit = {},
    val retry: () -> Unit = {},
    val grantShizuku: () -> Unit = {},
    val getShizuku: () -> Unit = {},
    val openShizuku: () -> Unit = {},
    val openBuildNumber: () -> Unit = {},
    val openWirelessDebugging: () -> Unit = {},
    val openTemplate: () -> Unit = {},
    val openTailscale: () -> Unit = {},
    val openUrl: (String) -> Unit = {},
    val testVoice: () -> Unit = {},
    val previewVoice: (String) -> Unit = {},
    val setWakeWord: (Boolean) -> Unit = {},
    val setVoiceEnabled: (Boolean) -> Unit = {},
    val copy: (String) -> Unit = {},
    val listen: () -> Unit = {},
    val micGranted: () -> Boolean = { false },
)
